### ISSUE TITLE
Not usuable in typescript projects

### ISSUE THREAD

**Issue by Tomato6966** [tga098/sharding-stats#17]
You are missing declaration types

**Comment by Tomato6966** [comment]
After adding this to your Project, then you can use the module!
![image](https://github.com/tga098/sharding-stats/assets/68145571/f637be3f-2ebf-499f-b5d6-33a6cac2edd0)

**Comment by tga098** [comment]
Sorry for that, I will try to fix that asap because this was a JS focused NPM Package
